name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Security Issues**: Do NOT report security bugs here. Email github@rozpuszczalny.com instead.

        **Feature Requests**: Use [Discussions](https://github.com/vrognas/positron-redmine/discussions) instead.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear, concise description of the bug
      placeholder: "Extension fails to..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug
      placeholder: |
        1. Configure Redmine URL: https://example.com
        2. Run command: Redmine: List open issues
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens

  - type: dropdown
    id: ide
    attributes:
      label: IDE
      options:
        - VS Code
        - Positron
        - Both
    validations:
      required: true

  - type: input
    id: ide-version
    attributes:
      label: IDE Version
      placeholder: "e.g., 1.95.3"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      placeholder: "e.g., 3.0.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: redmine-version
    attributes:
      label: Redmine Version
      placeholder: "e.g., 5.1.0 (if known)"

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: "Output panel logs (View > Output > Redmine)"
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, configuration details, etc.
